


DECLARE @ID BIGINT = NULL
DECLARE @Name NVARCHAR(50) = 'Name c28ca28c93c141f5ac7c1442e11a70a1'
 


IF(EXISTS(SELECT 1 FROM 
					[dbo].[ImportRunState]
				WHERE 
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM [dbo].[ImportRunState]
WHERE 
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 

END