


DECLARE @ID BIGINT = 323472
DECLARE @EntityTypeID BIGINT = NULL
DECLARE @CIK NVARCHAR(250) = 'CIK d1d8f4bf320246ea84b8233bd50ddaaf'
DECLARE @Name NVARCHAR(250) = 'Name d1d8f4bf320246ea84b8233bd50ddaaf'
DECLARE @TradingSymbol NVARCHAR(50) = 'TradingSymbol d1d8f4bf320246ea84b8233bd50ddaaf'
 

DELETE FROM [Entity]
FROM 
	[dbo].[Entity] e
WHERE
	(CASE WHEN @ID IS NOT NULL THEN (CASE WHEN [ID] = @ID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @EntityTypeID IS NOT NULL THEN (CASE WHEN [EntityTypeID] = @EntityTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CIK IS NOT NULL THEN (CASE WHEN [CIK] = @CIK THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @TradingSymbol IS NOT NULL THEN (CASE WHEN [TradingSymbol] = @TradingSymbol THEN 1 ELSE 0 END) ELSE 1 END) = 1 
