


DECLARE @ID BIGINT = NULL
DECLARE @EntityTypeID BIGINT = 1
DECLARE @CIK INT = 735
DECLARE @Name NVARCHAR(250) = 'Name b0f5c74af5374d68b863a3207a175683'
DECLARE @TradingSymbol NVARCHAR(50) = 'TradingSymbol b0f5c74af5374d68b863a3207a175683'
DECLARE @IsMonitored BIT = 1
 

DELETE FROM [Entity]
FROM 
	[dbo].[Entity] e
WHERE
	(CASE WHEN @EntityTypeID IS NOT NULL THEN (CASE WHEN [EntityTypeID] = @EntityTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CIK IS NOT NULL THEN (CASE WHEN [CIK] = @CIK THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @TradingSymbol IS NOT NULL THEN (CASE WHEN [TradingSymbol] = @TradingSymbol THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsMonitored IS NOT NULL THEN (CASE WHEN [IsMonitored] = @IsMonitored THEN 1 ELSE 0 END) ELSE 1 END) = 1 
