


-- original values --
DECLARE @ID BIGINT = NULL
DECLARE @IssuerID BIGINT = 100003
DECLARE @ReporterID BIGINT = 100013
DECLARE @IsOfficer BIT = 1
DECLARE @IsDirector BIT = 1
DECLARE @Is10PctHolder BIT = 1
DECLARE @IsOther BIT = 1
DECLARE @OtherText NVARCHAR(250) = 'OtherText a156a83b49984e13aa36c16eca8aa528'
DECLARE @OfficerTitle NVARCHAR(50) = 'OfficerTitle a156a83b49984e13aa36c16eca8aa528'
DECLARE @Date DATE = '9/21/2019'
 
-- updated values --

DECLARE @updID BIGINT = NULL
DECLARE @updIssuerID BIGINT = 100008
DECLARE @updReporterID BIGINT = 100003
DECLARE @updIsOfficer BIT = 1
DECLARE @updIsDirector BIT = 1
DECLARE @updIs10PctHolder BIT = 1
DECLARE @updIsOther BIT = 1
DECLARE @updOtherText NVARCHAR(250) = 'OtherText c268e54f65404093b67ecb0dfd2d949b'
DECLARE @updOfficerTitle NVARCHAR(50) = 'OfficerTitle c268e54f65404093b67ecb0dfd2d949b'
DECLARE @updDate DATE = '7/31/2022'
 

DECLARE @Fail AS BIT = 0

IF(NOT EXISTS(SELECT 1 FROM 
				[dbo].[Form4Report]
				WHERE 
	(CASE WHEN @updIssuerID IS NOT NULL THEN (CASE WHEN [IssuerID] = @updIssuerID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updReporterID IS NOT NULL THEN (CASE WHEN [ReporterID] = @updReporterID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updIsOfficer IS NOT NULL THEN (CASE WHEN [IsOfficer] = @updIsOfficer THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updIsDirector IS NOT NULL THEN (CASE WHEN [IsDirector] = @updIsDirector THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updIs10PctHolder IS NOT NULL THEN (CASE WHEN [Is10PctHolder] = @updIs10PctHolder THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updIsOther IS NOT NULL THEN (CASE WHEN [IsOther] = @updIsOther THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updOtherText IS NOT NULL THEN (CASE WHEN [OtherText] = @updOtherText THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updOfficerTitle IS NOT NULL THEN (CASE WHEN [OfficerTitle] = @updOfficerTitle THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updDate IS NOT NULL THEN (CASE WHEN [Date] = @updDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM 
	[dbo].[Form4Report]
	WHERE 
	(CASE WHEN @IssuerID IS NOT NULL THEN (CASE WHEN [IssuerID] = @IssuerID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ReporterID IS NOT NULL THEN (CASE WHEN [ReporterID] = @ReporterID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsOfficer IS NOT NULL THEN (CASE WHEN [IsOfficer] = @IsOfficer THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsDirector IS NOT NULL THEN (CASE WHEN [IsDirector] = @IsDirector THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Is10PctHolder IS NOT NULL THEN (CASE WHEN [Is10PctHolder] = @Is10PctHolder THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsOther IS NOT NULL THEN (CASE WHEN [IsOther] = @IsOther THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @OtherText IS NOT NULL THEN (CASE WHEN [OtherText] = @OtherText THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @OfficerTitle IS NOT NULL THEN (CASE WHEN [OfficerTitle] = @OfficerTitle THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Date IS NOT NULL THEN (CASE WHEN [Date] = @Date THEN 1 ELSE 0 END) ELSE 1 END) = 1 

	SET @Fail = 1
END
ELSE
BEGIN
DELETE FROM 
	[dbo].[Form4Report]
	WHERE 
	(CASE WHEN @updIssuerID IS NOT NULL THEN (CASE WHEN [IssuerID] = @updIssuerID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updReporterID IS NOT NULL THEN (CASE WHEN [ReporterID] = @updReporterID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updIsOfficer IS NOT NULL THEN (CASE WHEN [IsOfficer] = @updIsOfficer THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updIsDirector IS NOT NULL THEN (CASE WHEN [IsDirector] = @updIsDirector THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updIs10PctHolder IS NOT NULL THEN (CASE WHEN [Is10PctHolder] = @updIs10PctHolder THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updIsOther IS NOT NULL THEN (CASE WHEN [IsOther] = @updIsOther THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updOtherText IS NOT NULL THEN (CASE WHEN [OtherText] = @updOtherText THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updOfficerTitle IS NOT NULL THEN (CASE WHEN [OfficerTitle] = @updOfficerTitle THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updDate IS NOT NULL THEN (CASE WHEN [Date] = @updDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 
END


IF(@Fail = 1) 
BEGIN
	THROW 51001, 'Form4Report was not updated', 1
END