


-- original values --
DECLARE @ID BIGINT = 890747
DECLARE @EntityTypeID BIGINT = NULL
DECLARE @CIK NVARCHAR(250) = 'CIK 52ea2c70817c4844911a712e85e0e33e'
DECLARE @Name NVARCHAR(250) = 'Name 52ea2c70817c4844911a712e85e0e33e'
DECLARE @TradingSymbol NVARCHAR(50) = 'TradingSymbol 52ea2c70817c4844911a712e85e0e33e'
 
-- updated values --

DECLARE @updID BIGINT = 890747
DECLARE @updEntityTypeID BIGINT = NULL
DECLARE @updCIK NVARCHAR(250) = 'CIK 948ff2c72e1e4918af8e10dc67ed125b'
DECLARE @updName NVARCHAR(250) = 'Name 948ff2c72e1e4918af8e10dc67ed125b'
DECLARE @updTradingSymbol NVARCHAR(50) = 'TradingSymbol 948ff2c72e1e4918af8e10dc67ed125b'
 

DECLARE @Fail AS BIT = 0

IF(NOT EXISTS(SELECT 1 FROM 
				[dbo].[Entity]
				WHERE 
	(CASE WHEN @updID IS NOT NULL THEN (CASE WHEN [ID] = @updID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updEntityTypeID IS NOT NULL THEN (CASE WHEN [EntityTypeID] = @updEntityTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCIK IS NOT NULL THEN (CASE WHEN [CIK] = @updCIK THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updName IS NOT NULL THEN (CASE WHEN [Name] = @updName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updTradingSymbol IS NOT NULL THEN (CASE WHEN [TradingSymbol] = @updTradingSymbol THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM 
	[dbo].[Entity]
	WHERE 
	(CASE WHEN @ID IS NOT NULL THEN (CASE WHEN [ID] = @ID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @EntityTypeID IS NOT NULL THEN (CASE WHEN [EntityTypeID] = @EntityTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CIK IS NOT NULL THEN (CASE WHEN [CIK] = @CIK THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @TradingSymbol IS NOT NULL THEN (CASE WHEN [TradingSymbol] = @TradingSymbol THEN 1 ELSE 0 END) ELSE 1 END) = 1 

	SET @Fail = 1
END
ELSE
BEGIN
DELETE FROM 
	[dbo].[Entity]
	WHERE 
	(CASE WHEN @updID IS NOT NULL THEN (CASE WHEN [ID] = @updID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updEntityTypeID IS NOT NULL THEN (CASE WHEN [EntityTypeID] = @updEntityTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCIK IS NOT NULL THEN (CASE WHEN [CIK] = @updCIK THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updName IS NOT NULL THEN (CASE WHEN [Name] = @updName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updTradingSymbol IS NOT NULL THEN (CASE WHEN [TradingSymbol] = @updTradingSymbol THEN 1 ELSE 0 END) ELSE 1 END) = 1 
END


IF(@Fail = 1) 
BEGIN
	THROW 51001, 'Entity was not updated', 1
END